<?php

namespace AppBundle\Repository;

/**
 * FrereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrereRepository extends \Doctrine\ORM\EntityRepository
{
}
